services:
  - mysql:latest
image: php:7.1-apache
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: el_duderino
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  
test:
  script:
  - php -v
