services:
  - mysql:latest
image: danpospisil/laravel-testing:0.1
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: $TEST_MYSQL_DB
  MYSQL_ROOT_PASSWORD: $TEST_MYSQL_PASS
  
test:
  script:
  - php -v
  - ls -l
  tags:
    - testdo
  environment:
    name: Testing
